#!/usr/bin/env bash
command=$1

CLI_FOLDER="$( cd "$( dirname "$0" )" && pwd )"
PATH="$PATH:$CLI_FOLDER"

TASKS_FOLDER="/tasks"
TASK_FOLDER="$PWD"
TASK_FILE="$TASK_FOLDER/task"

case "$command" in

help)
  echo "Доступные команды:

    list        - Показать список задач
    task        - Показать текущую задачу
    next        - Перейти к следующей задаче
    prev        - Перейти к предыдущей задаче

    h           - Показать эту подсказку"
;;

list)
  find $TASKS_FOLDER -name task | sort | xargs -I{} sh -c "dirname {} | xargs basename | xargs -I{} echo -n '{}. '; cat {}"
  # find $TASKS_FOLDER -name task | sort | xargs cat
;;

task)
  if [ -f task ]; then
    echo -n "`pwd | xargs basename`. " 2>/dev/null
    cat "$TASK_FILE" 2>/dev/null
  fi
;;

next-path)
  task_path="/tasks/$(ls -F /tasks | grep '/' | grep -A1 -xF "$(basename `pwd`)/" | tail -1)"
  if [ $task_path = '/tasks/' ]; then
    task_path="/tasks/$(ls -F /tasks | grep '/' | head -1 )"
  fi
  echo $task_path
;;

prev-path)
  task_path="/tasks/$(ls -F /tasks | grep '/' | grep -B1 -xF "$(basename `pwd`)/" | head -1)"
  if [ $task_path = '/tasks/' ]; then
    task_path="/tasks/$(ls -F /tasks | grep '/' | tail -1 )"
  fi
  echo $task_path
;;

*)

  echo "`$0 help`"
  exit 1

;;
esac

exit 0