#!/usr/bin/env bash
command=$1

CLI_FOLDER="$( cd "$( dirname "$0" )" && pwd )"
PATH="$PATH:$CLI_FOLDER"

TASKS_FOLDER="/tasks"
TASK_FOLDER="$PWD"
TASK_FILE="$TASK_FOLDER/task"

case "$command" in

help)
  echo "Доступные команды:

    list        - Показать список задач
    task        - Показать текущую задачу или задачу с номером N
    next        - Перейти к следующей задаче
    prev        - Перейти к предыдущей задаче
    goto N      - Перейти к задаче N

    h           - Показать эту подсказку"
;;

list)
  find $TASKS_FOLDER -name task | sort | xargs cat
;;

task)
  cat "$TASK_FILE" 2>/dev/null
;;

next)
  $0 task
;;

prev)
  $0 task
;;

goto)
  $0 task
;;

*)

  echo "`$0 help`"
  exit 1

;;
esac

exit 0