#!/usr/bin/env bash

# Переключается между уроками

current_folder=`dirname "$0"`
tasks_folder="$current_folder/../tasks"
task_folder="$tasks_folder/$1"

if ! [ -d $task_folder ]; then
  echo "task is not found" >&2
  echo "available tasks are" >&2
  echo `ls -1 $tasks_folder` >&2
  exit 1
fi

echo $1 > "$current_folder/tid"
# cat "$current_folder/tid"
cat "$task_folder/task"

# echo
# cp -a "$task_folder/." .