#!/usr/bin/env bash

# Выводит текущую задачу

current_folder=`dirname "$0"`

if ! [ -d "$current_folder/tid" ]; then
  echo 1 > "$current_folder/tid"
fi

task_id=${1:-`cat "$current_folder/tid"`}
tasks_folder="$current_folder/../tasks"
task_folder="$tasks_folder/$task_id"

if ! [ -d "$task_folder" ]; then
  echo "lesson '$task_id' is not found" >&2
  echo "available lessons are" >&2
  echo `ls -1 $tasks_folder` >&2
  exit 1
fi

cat "$task_folder/task"